
<field:banben itemname="版本类型" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:banben>

<field:jianjie itemname="简介" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jianjie>

<field:dizhi itemname="外部视频" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:dizhi>

<field:bendi itemname="本地视频" autofield="1" notsend="0" type="media" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:bendi>

<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:body>

<field:liebiao itemname="播放列表" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:liebiao>

