
  <m:item name='网站栏目管理' link='catalog_main.php' ischannel='1' addalt='创建栏目' linkadd='catalog_add.php?listtype=all' rank='t_List,t_AccList' target='main' />
  <m:item name='所有档案列表' link='content_list.php' rank='a_List,a_AccList' target='main' />
  <m:item name='内容回收站' link='recycling.php' ischannel='1' addalt='清空回收站' addico='images/gtk-del.png' linkadd='archives_do.php?dopost=clear&aid=no&recycle=1' rank='a_List,a_AccList,a_MyList' target='main' />
  
  
   <m:item name='LOGO管理' link='ppt_edit.php?aid=1&dopost=edit' target='main' />
    <m:item name='播放页面二维码图片' link='ad_edit.php?aid=24&dopost=edit' target='main' />
	 <m:item name='跳转页二维码' link='file_manage_main.php?activepath=%2Fimages%2Fweixin' target='main' />
	  <m:item name='播放器上方广告' link='ad_edit.php?aid=21&dopost=edit' target='main' />
	   <m:item name='播放器下方广告' link='ad_edit.php?aid=22&dopost=edit' target='main' />
	    <m:item name='底部悬浮广告' link='ad_edit.php?aid=23&dopost=edit' target='main' />
