<?php
$z[0]=Array("field","",432,451);
$z[0][4]['name']="title";
$z[1]=Array("global","",452,478);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",519,541);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",581,632);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",727,759);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",825,857);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",894,929);
$z[6][4]['filename']="head.htm";
$z[7]=Array("field","",1240,1256);
$z[7][4]['name']="id";
$z[8]=Array("php","\$bo = \$_GET[bo];echo \$bo;",1510,1556);
$z[9]=Array("php","\$bo = \$_GET[bo];echo \$bo;",1623,1669);
$z[10]=Array("field","",1928,1975);
$z[10][4]['name']="liebiao";
$z[10][4]['function']="GetMurlss(@me)";
$z[11]=Array("global","",2302,2334);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("global","",2463,2495);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",2606,2631);
$z[13][4]['name']="cfg_weixin";

?>