<?php
$z[0]=Array("channel","\r\n<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n",75,260);
$z[0][4]['type']="top";
$z[0][4]['row']="4";
$z[0][4]['currentstyle']="<li class='current'><a href='~typelink~'>~typename~</a></li>";
$z[1]=Array("global","",385,417);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",499,525);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",564,591);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("global","",645,670);
$z[4][4]['name']="cfg_weixin";

?>