<?php
$z[0]=Array("channel","\r\n<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n",733,918);
$z[0][4]['type']="top";
$z[0][4]['row']="4";
$z[0][4]['currentstyle']="<li class='current'><a href='~typelink~'>~typename~</a></li>";
$z[1]=Array("myppt","<a href=\"[field:url/]\"><img src=\"[field:pic/]\"></a>",1021,1116);
$z[1][4]['tyepid']="1";
$z[1][4]['row']="1";
$z[2]=Array("global","",1162,1188);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",1227,1254);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("global","",1308,1333);
$z[4][4]['name']="cfg_weixin";

?>