<?php
$z[0]=Array("global","",578,610);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",663,695);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",744,776);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",848,880);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",908,934);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",978,1008);
$z[5][4]['name']="cfg_description";
$z[6]=Array("global","",1045,1072);
$z[6][4]['name']="cfg_keywords";
$z[7]=Array("include","",1132,1168);
$z[7][4]['filename']="head1.htm";
$z[8]=Array("arclist","\r\n<a class=\"list_item js_post\" href=\"[field:arcurl/]\">\r\n\r\n		<div class=\"cover\">\r\n\r\n			<img class=\"img js_img\" src=\"[field:litpic/]\" alt=\"\">\r\n\r\n		</div>\r\n\r\n		<div class=\"cont\">\r\n\r\n			<h2 class=\"title js_title\">[field:title/]</h2>\r\n\r\n			<p class=\"desc\">类 型：[field:banben/]</p>\r\n\r\n			<p class=\"desc\">简 介：[field:jianjie function=\"html2text(cn_substr('@me',200))\"/] </p>\r\n\r\n			\r\n\r\n		</div>\r\n\r\n	</a>\r\n",1334,1835);
$z[8][4]['row']="20";
$z[8][4]['titlelen']="60";
$z[8][4]['channelid']="17";
$z[8][4]['addfields']="banben,jianjie";
$z[9]=Array("global","",1901,1927);
$z[9][4]['name']="cfg_powerby";

?>